import {
  Alfa_Slab_One,
  Fugaz_One,
  Geist,
  Geist_Mono,
  Pacifico,
  Poppins,
} from "next/font/google";
import "./globals.css";
import QueryProvider from "./providers/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

const pacifico = Pacifico({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-pacifico",
});

const fugaz = Fugaz_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-fugaz",
});

const alfa = Alfa_Slab_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-alfa",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable}
        ${pacifico.variable}
        ${fugaz.variable}
        ${alfa.variable} h-full antialiased`}
    >
      <body className="flex flex-col min-h-full">
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
